title: Artur F. C. Rosa
description: Artigos sobre desenvolvimento web

url: http://localhost:4000
baseurl: ""
paginate_path: "blog/page-:num/"
permalink: ":title/"

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
   github: arturcorvino
   twitter: arturcrosa
   facebook: arturcrosa
   email: artur.corvino1@gmail.com

google_analytics: "UA-58263416-1"
