title: Artur F. C. Rosa
description: Artigos sobre desenvolvimento web

url: http://arturcorvino/github.io
baseurl: "/blog"
paginate_path: "page-:num/"
permalink: "post/:title/"

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Página Inicial
   url: /blog
 - title: Sobre
   url: /about

social:
   github: arturcorvino
   twitter: arturcrosa
   facebook: arturcrosa
   email: artur.corvino1@gmail.com

google_analytics: "UA-62498663-3"
